version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: bocauser
      POSTGRES_PASSWORD: boca
      POSTGRES_DB: bocadb
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: bocadb
      DB_USER: bocauser
      DB_PASSWORD: boca
    restart: always

volumes:
  db_data: {}
